name: BlockyDynmap
main: com.blockycraft.blockydynmap.BlockyDynmap
version: 1.0.0
author: Bernardo Zukerman
description: Integra BlockyClaim e BlockyGroups com o Dynmap.

softdepend: [dynmap, BlockyClaim, BlockyGroups]